import Foundation

// MARK: - Bundled workout catalog (Stage A of the content pipeline)
//
// The browsable "Discover" catalog ships as Resources/MorpheCatalog.json,
// generated by Tools/generate_catalog.py from the real exercise library —
// content as data, not code. When the Firebase backend lands, the same
// document shape moves to a `workouts` collection and this loader becomes
// the offline cache; the feed then adds engagement-ranked ordering.
//
// Honest labeling: these are Morphe Programs. Creator attribution arrives
// only when real coaches publish through the marketplace.

/// One workout document in the bundled catalog.
struct CatalogWorkout: Codable, Identifiable, Hashable {
    struct CatalogExercise: Codable, Hashable {
        var libraryID: String
        var sets: Int
        var reps: Int
    }

    var id: String                 // stable UUID string (uuid5 of the combo key)
    var name: String
    var focus: String              // Full Body / Push / Pull / Legs / Core / Conditioning / Recovery
    var level: String              // DemoDifficulty rawValue
    var durationMinutes: Int
    var equipmentProfile: String   // Bodyweight / Dumbbells / Full Gym
    var goal: String
    var notes: String
    /// Curated collection name ("Legends"); nil = generated Morphe Program.
    var collection: String?
    var exercises: [CatalogExercise]
}

struct WorkoutCatalogFile: Codable {
    var version: Int
    var workouts: [CatalogWorkout]
}

enum WorkoutCatalog {
    /// Loads the bundled catalog; returns an empty list (never crashes) if the
    /// resource is missing or unreadable.
    static func loadBundled() -> [CatalogWorkout] {
        guard let url = Bundle.main.url(forResource: "MorpheCatalog", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(WorkoutCatalogFile.self, from: data)
        else { return [] }
        return file.workouts
    }

    /// Maps a catalog document onto the app's runtime template, resolving each
    /// exercise against the library. Returns nil if ANY exercise is missing —
    /// a catalog workout with holes teaches nothing.
    static func template(from workout: CatalogWorkout, library: [ExerciseReference]) -> WorkoutTemplate? {
        guard let templateID = UUID(uuidString: workout.id) else { return nil }

        var exercises: [WorkoutExercise] = []
        for (index, entry) in workout.exercises.enumerated() {
            guard let reference = library.first(where: { $0.id == entry.libraryID }) else { return nil }
            exercises.append(
                WorkoutExercise(
                    // Deterministic per-workout id so tracked sets reattach
                    // across relaunches (same rule as custom workouts).
                    id: "\(workout.id)-\(index)",
                    exerciseLibraryID: reference.id,
                    name: reference.name,
                    muscleGroup: reference.muscleGroup,
                    sets: "\(entry.sets) sets",
                    reps: "\(entry.reps) reps",
                    difficulty: reference.difficulty,
                    formCue: reference.formCue
                )
            )
        }

        return WorkoutTemplate(
            id: templateID,
            name: workout.name,
            type: workout.collection ?? "Morphe Program",
            sport: .generalFitness,
            category: category(for: workout.focus),
            sessionType: workout.focus == "Recovery" ? .recoverySession : .gymWorkout,
            goal: workout.goal,
            difficulty: DemoDifficulty(rawValue: workout.level) ?? .moderate,
            durationMinutes: workout.durationMinutes,
            equipment: workout.equipmentProfile,
            focusTag: workout.focus,
            exercises: exercises,
            notes: workout.notes,
            coachNote: workout.notes
        )
    }

    private static func category(for focus: String) -> ProgramCategory {
        switch focus {
        case "Conditioning": return .conditioning
        case "Recovery": return .recovery
        default: return .strength
        }
    }
}
